TextureCursorMouseMove: ImageData.c main.c ImageIO.c TextureImage.c ImageData.h ImageIO.h TextureImage.h
	cc -o TextureCursorMouseMove ImageData.c main.c TextureImage.c ImageIO.c ImageData.h ImageIO.h TextureImage.h -L. -lglut  -lGL  -lGLU  -lXi  -lXrandr  -lm

