ImageAnimation: ImageData.c main.c ImageIO.c GenericTimer.c GenericTimer.h
	cc -o ImageAnimation ImageData.c main.c ImageIO.c GenericTimer.c GenericTimer.h -L. -lglut  -lGL  -lGLU  -lXi  -lXrandr  -lm

